**Soru-1 :** 
    
    Bir NumPy dizisi oluşturun ve elemanlarını ekrana yazdırın.

In [7]:
import numpy as np

In [9]:
nump_arr = np.array([0.0,1.0,2,3,4,5])

In [11]:
nump_arr

array([0., 1., 2., 3., 4., 5.])

In [13]:
nump_arr.shape

(6,)

**Soru-2 :** 

    Bir dizi oluşturun ve veri tipini kontrol edin.


In [22]:
nump_arr1 = np.logspace(1,3,5)

In [24]:
nump_arr1

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [46]:
nump_arr1.dtype

dtype('float64')

**Soru-3 :** 

    0'dan 10'a kadar 5 eşit aralıklı sayı içeren bir dizi oluşturun.

In [30]:
nump_arr3 = np.linspace(0,10,5)

In [52]:
nump_arr3

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Soru-4 :**

    5x5 boyutunda sadece 1'lerden oluşan bir matris oluşturun.

In [75]:
nump_arr4 = np.ones([5,5])

In [77]:
nump_arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Soru-5 :** 

    0 ile 1 arasında rastgele sayılardan oluşan bir dizi oluşturun.

In [73]:
pass

**Soru-6 :**

    Bir dizinin maksimum, minimum ve ortalama değerlerini bulun.

In [83]:
nump_arr6 = np.arange(1,100,5)

In [87]:
nump_arr6

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [99]:
nump_arr6.max() # Maximum Değer

np.int64(96)

In [101]:
nump_arr6.min() # Minimum Değer

np.int64(1)

In [103]:
nump_arr6.mean() # Ortalama Değer

np.float64(48.5)

**Soru-7 :**

    Bir diziyi yeniden şekillendirin (reshape).

In [112]:
nump_arr7 = np.zeros([10,10])

In [114]:
nump_arr7

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [306]:
nump_arr7.reshape(4,5,5) # Derinliği 4, row(satır) sayısı 5 olan ve 5 column(sütun) dan oluşan bir reshape() kullanımı...

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [126]:
nump_arr7.reshape(-1,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Not :**

    Parant.içerisinde ilk parametre değerine yazılan -1 ile oluşturulmak istenen şey ; ifade 5 column(sütun)  dan oluşsun ve row(satır) sayısını sen kendin oluştur demiş olduk.

In [131]:
nump_arr7.reshape(4,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Not :**

    Parantez içerisine yazılan 4 ile ifadenenin 4 row(satır) dan oluşturulmasını istedik.Ardından yazılan -1 değeri ile column(sütun) sayısının otomatik olarak eleman sayısına uygun olacak şekilde sistem tarafından oluşturulmasını istedik

**Soru-8 :**

    Belirli bir değerle bir dizi oluşturun (full).

In [388]:
nump_arr8 = np.ones((100,), ndmin=3) * 100

TypeError: ones() got an unexpected keyword argument 'ndmin'

**Hata Açıklama :**

    np.ones fonksiyonu ndmin argümanını kabul etmiyor. Eğer ndmin argümanını kullanmak istiyorsanız, np.array fonksiyonunu kullanabilirsiniz. İşte doğru şekilde nasıl yapabileceğinizi gösteren örnek:

In [422]:
nump_arr8 = np.array(np.ones(100)*100,ndmin=3)

**Soru-9 :**

    np.linspace() fonksiyonunu kullanarak bir dizi oluşturun.
    Bu dizinin veri tipini kontrol edin.
    Sonrasında dizinin veri tipini orijinal veri tipinden daha alt bir tipi olacak şekilde yeniden tanımlayınız.

In [428]:
nump_arr9 = np.linspace(1,5,num=10)

In [430]:
nump_arr9

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [432]:
nump_arr9.dtype

dtype('float64')

In [436]:
np.array(nump_arr9,dtype="float16")

array([1.   , 1.444, 1.889, 2.334, 2.777, 3.223, 3.666, 4.11 , 4.555,
       5.   ], dtype=float16)

**Soru-10 :**

    Bir Numpy array i oluşturun.Oluşturduğunuz bu array in veri tipini kontrol edin.
    Sonrasında bu array in dtype ını kısayoldan değiştirerek yeni bir array e assign edin.

In [446]:
nump_arr10 = np.array(np.logspace(1,3,10))

In [448]:
nump_arr10

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [452]:
nump_arr10.dtype

dtype('float64')

In [458]:
as_nump_arr10 = nump_arr10.astype("int16")

In [460]:
as_nump_arr10

array([  10,   16,   27,   46,   77,  129,  215,  359,  599, 1000],
      dtype=int16)

**Soru-11 :**

    Elemanları arasındaki fark lineer olarak artan,10 ile 15 arasındaki sayılardan oluşan 10 elemanlı bir Numpy dizisi oluşturun.Oluşturduğunuz bu dizinin hem şeklini hem de boyutunu dizinin eleman sayısına bakmaksızın değiştirip yeni dizinin hem şekil-boyut bilgisini hem de veri tipini yazdırınız.

In [544]:
nump_arr11 = np.linspace(10,15,10,retstep=True) 

In [546]:
nump_arr11

(array([10.        , 10.55555556, 11.11111111, 11.66666667, 12.22222222,
        12.77777778, 13.33333333, 13.88888889, 14.44444444, 15.        ]),
 np.float64(0.5555555555555556))

### Not : 
Parantez içerisine yazılan **retstep=True** parametresinin **default değeri retstep=False** olup ifade içerisinde gizlidir.Ancak parametreyi parantez içerisinde **retstep=True** olarak yazılması durumunda bize sayılar arasındaki artış miktarını da dizi ile birlikte return eder.

In [481]:
np.resize(nump_arr11,(3,5,5))

array([[[10.        , 10.55555556, 11.11111111, 11.66666667,
         12.22222222],
        [12.77777778, 13.33333333, 13.88888889, 14.44444444,
         15.        ],
        [10.        , 10.55555556, 11.11111111, 11.66666667,
         12.22222222],
        [12.77777778, 13.33333333, 13.88888889, 14.44444444,
         15.        ],
        [10.        , 10.55555556, 11.11111111, 11.66666667,
         12.22222222]],

       [[12.77777778, 13.33333333, 13.88888889, 14.44444444,
         15.        ],
        [10.        , 10.55555556, 11.11111111, 11.66666667,
         12.22222222],
        [12.77777778, 13.33333333, 13.88888889, 14.44444444,
         15.        ],
        [10.        , 10.55555556, 11.11111111, 11.66666667,
         12.22222222],
        [12.77777778, 13.33333333, 13.88888889, 14.44444444,
         15.        ]],

       [[10.        , 10.55555556, 11.11111111, 11.66666667,
         12.22222222],
        [12.77777778, 13.33333333, 13.88888889, 14.44444444,
         15

In [483]:
np.resize(nump_arr11,(3,5,5)).shape

(3, 5, 5)

In [485]:
np.resize(nump_arr11,(3,5,5)).dtype

dtype('float64')

**Soru-12 :**

    Elemanları 0-20 arasında olacak şekilde 20 den başlayıp 0 a kadar 2 şer 2 şer azalan elemanlardan oluşan bir numpy dizisini uygun metodu kullanarak oluşturunuz.
    Ardından dizi içerisinde yer alan elemanlardan 10-0 arasındaki çift sayıları slicingleyerek başka bir dizinin elemanları olarak atayınız.
    En son oluşturduğunuz dizinin tüm elemanlarını da -100 olarak değiştiriniz.
    Not: Yeni oluşturulan dizide yapılacak işlemler eski diziyi etkilemeyecek şekilde olmalıdır.
    

In [492]:
nump_arr12 = np.arange(20,0,-2)

In [498]:
copy_nump_arr12 = nump_arr12.copy()

In [514]:
copy_nump_arr12

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [524]:
copy_nump_arr12[:4:-1]

array([ 2,  4,  6,  8, 10])

In [526]:
slicing_copy_num_arr12 = copy_nump_arr12[:4:-1]

In [533]:
slicing_copy_num_arr12[::] = -100

In [535]:
slicing_copy_num_arr12

array([-100, -100, -100, -100, -100])

In [537]:
copy_nump_arr12

array([  20,   18,   16,   14,   12, -100, -100, -100, -100, -100])

In [539]:
nump_arr12

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**Soru-13 :**

    log10_2 ile log10_3 arasında yer alan ve logaritmik olarak 5 elemanlı bir dizi oluşturunuz.

In [575]:
nump_arr13 = np.logspace(2,3,5)


In [577]:
nump_arr13

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

**Soru-14 :**

    Elemanları 1 lerden oluşan 3 derinlikli 10 row ve 10 column a sahip bir numpy dizisi oluşturunuz. >>> np.ones()

In [585]:
np.ones((3,10,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

**Soru-15 :**

    Elemanları 0 ile 100 arasında 30 elemanlı;3 derinlik,5 satır(row) ve 2 sütun(column) a sahip bir numpy dizisi oluşturup ardından bu diziyle aynı derinlik satır ve sütun değerine sahip olan,ancak elemanları sadece 1 lerden oluşan bir numpy dizisi oluşturunuz.

In [609]:
nump_arr15 = np.linspace(0,100,30,dtype="int16")

In [613]:
nump_arr15.resize(3,5,2)

In [615]:
nump_arr15

array([[[  0,   3],
        [  6,  10],
        [ 13,  17],
        [ 20,  24],
        [ 27,  31]],

       [[ 34,  37],
        [ 41,  44],
        [ 48,  51],
        [ 55,  58],
        [ 62,  65]],

       [[ 68,  72],
        [ 75,  79],
        [ 82,  86],
        [ 89,  93],
        [ 96, 100]]], dtype=int16)

In [619]:
nump_arr15.shape

(3, 5, 2)

In [621]:
np.ones_like(nump_arr15)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [631]:
np.ones_like(nump_arr15).shape

(3, 5, 2)

**Soru-16 :**

    Elemanları 0 ile 20 arasında ve lineer olarak artan 27 elemanlı;9 derinlik,1 satır(row) ve 3 sütun(column) a sahip bir lineer dizi oluşturup ardından bu diziyle aynı derinlik satır ve sütun değerine sahip olan,ancak elemanları sadece 0 larden oluşan bir numpy dizisi oluşturunuz.

In [650]:
nump_arr16 = np.linspace(0,20,27)

In [652]:
nump_arr16.resize(9,1,3)

In [654]:
nump_arr16

array([[[ 0.        ,  0.76923077,  1.53846154]],

       [[ 2.30769231,  3.07692308,  3.84615385]],

       [[ 4.61538462,  5.38461538,  6.15384615]],

       [[ 6.92307692,  7.69230769,  8.46153846]],

       [[ 9.23076923, 10.        , 10.76923077]],

       [[11.53846154, 12.30769231, 13.07692308]],

       [[13.84615385, 14.61538462, 15.38461538]],

       [[16.15384615, 16.92307692, 17.69230769]],

       [[18.46153846, 19.23076923, 20.        ]]])

In [656]:
nump_arr16.shape

(9, 1, 3)

In [659]:
np.zeros_like(nump_array16)

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [661]:
np.zeros_like(nump_array16).shape

(9, 1, 3)

**Soru-17:**

    Ana köşegenlerinden bir sonraki elemanları 1 lerden oluşan ve diğer tüm elemanları 0 olan 3 satır(row) ve 3 sütun(column) a sahip bir matris oluşturunuz.

In [670]:
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

**Soru-18 :**

    Verilen bir dizinin şekli ve türüne sahip, ancak 5 değeri ile doldurulmuş bir dizi oluşturunuz.

In [712]:
np.full(7,15)

array([15, 15, 15, 15, 15, 15, 15])

In [718]:
np.full_like(np.full(7,15),33)

array([33, 33, 33, 33, 33, 33, 33])